//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantMenuManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderModel
    {
        public OrderModel()
        {
            this.MenuModels = new HashSet<MenuModel>();
        }
    
        public int ID { get; set; }
        public System.DateTime WhenOrdered { get; set; }
        public string ClientName { get; set; }
        public string MenuName { get; set; }
        public int Bill { get; set; }
    
        public virtual ICollection<MenuModel> MenuModels { get; set; }
    }
}
