//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantMenuManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReclamationModel
    {
        public int ID { get; set; }
        public string ClientName { get; set; }
        public System.DateTime WhenOrdered { get; set; }
        public System.DateTime When { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
    }
}
